### 
GET http://127.0.0.1:5000/health
### 
GET http://127.0.0.1:5000/items
Cookie: session=...

### 
GET http://127.0.0.1:5000/files
Cookie: session=...

### 
GET http://127.0.0.1:5000/items/1
Cookie: session=...

### 
GET http://127.0.0.1:5000/items/1/todos
Cookie: session=...

### 
GET http://127.0.0.1:5000/docs

### 
POST http://127.0.0.1:5000/items 
Content-Type: application/json 

{ "name": "whatup"}

### POST fail
POST http://127.0.0.1:5000/items 
Content-Type: application/json 

{ "name": [1]}

###
DELETE http://127.0.0.1:5000/items/1





### 
GET http://127.0.0.1:5000/accounts

###
POST http://127.0.0.1:5000/accounts/login 
Content-Type: application/json 

{ "username": "admin", "password": "admin"}

### 
GET http://127.0.0.1:5000/accounts/logout

###
POST http://127.0.0.1:5000/accounts/register 
Content-Type: application/json 

{ "username": "admin3", "password": "admin", "invitationCode": "1234"}

###
POST http://127.0.0.1:5000/accounts/1/changePassword 
Content-Type: application/json 
Cookie: session=rux...

{ "oldPassword": "admin", "newPassword": "admin" }

